#!name=ClawRocket AdBlock
#!desc=微博开屏广告拦截
#!author=Clawbaby
#!version=1.0.0

[URL Rewrite]
^https?://bootpreload\.uve\.weibo\.com reject
^https?://wbapp\.uve\.weibo\.com reject
^https?://kadimage\.biz\.weibo\.com reject
^https?://brandvideo\.biz\.weibo\.com reject
^https?://sdkclick\.biz\.weibo\.com reject
^https?://sdkaction\.biz\.weibo\.com reject
^https?://sdkmonitor\.biz\.weibo\.com reject
^https?://api\.im\.weibo\.cn reject
^https?://dp\.im\.weibo\.cn reject
^https?://gateway\.im\.weibo\.cn reject
^https?://biz\.weibo\.com reject
^https?://im\.weibo\.cn reject
^https?://ad\.weibo\.com reject
^https?://alitui\.weibo\.com reject
^https?://tui\.weibo\.com reject
^https?://push\.weibo\.com reject
^https?://uve\.weibo\.com reject
^https?://wax\.weibo\.cn reject
^https?://zymo\.mps\.weibo\.com reject
^https?://.*\.snssdk\.com/api/ads reject
^https?://.*\.amemv\.com/api/ads reject
^https?://ads.*\.zijieapi\.com reject
^https?://api\.zhihu\.com/topstory/recommend reject
^https?://app\.bilibili\.com/x/v2/splash reject
^https?://edith\.xiaohongshu\.com reject
